name: Setup OpenVicProject Build Cache
description: Setup OpenVicProject Build Cache
inputs:
  cache-name:
    description: The cache base name (job name by default).
    default: "${{github.job}}"
  base-branch:
    description: The branch to base the cache upon.
    default: "master"
  scons-cache:
    description: The scons cache path.
    default: "${{github.workspace}}/.scons-cache/"
runs:
  using: "composite"
  steps:
    # Upload cache on completion and check it out now
    - name: Load .scons_cache directory
      uses: actions/cache@v3
      with:
        path: ${{inputs.scons-cache}}
        key: ${{inputs.cache-name}}-${{inputs.base-branch}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{inputs.cache-name}}-${{inputs.base-branch}}-${{github.ref}}-${{github.sha}}
          ${{inputs.cache-name}}-${{inputs.base-branch}}-${{github.ref}}
          ${{inputs.cache-name}}-${{inputs.base-branch}}
